#!/bin/bash
#Functions extractor for Lazass
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

##########################################
#Extract all functions from bash scripts
#$1: File
#$2: Function
extract_all_functions() {
	cat $1 |grep "() {"|sed 's/() {/ /'
}


is_necessary=0
echo "#!/bin/bash" >> variables.txt
extractfromto lib/lazass "## LAZASS LIBRARY ##" "## VARIABLES ##" >> variables.txt

description "Inject Lazass Functions"
listecho "$1 will work without Lazass lib after this"
nlbecho "This will";nlbecho "erased" $ERR;colecho "all previous version of the functions"
continue_prompt
messagebox "Seeking Functions in $1"

functions=$(extract_all_functions lib/lazass)
#Functions extractor for the scripts
for lazass_function in $functions
do
	
	#Seek the functions
	searchstring $1 $lazass_function
	if [ $found == 0 ]
		then
		is_necessary=1
		extractfunction lib/lazass $lazass_function >> functions.txt
	fi
done


if [ $is_necessary != 0 ]
	then
	alreadycopied=$(extract_all_functions functions.txt)

	messagebox "Seeking Functions dependancy"
#Functions extractor for functions
for lazass_function_dependency in $functions
do
	searchstring functions.txt $lazass_function_dependency > /dev/null
	if [ $found == 0 ]
		then
		echo $alreadycopied |grep -q $lazass_function_dependency
		if [ "$?" -ne "0" ]
			then
			listecho "$lazass_function_dependency founded"
			extractfunction lib/lazass $lazass_function_dependency >> functions_dep.txt
		fi
	fi
done


line_break
colecho "This script seems to use LAZASS" $OK
erasefromto $1 "## LAZASS LIBRARY ##" "############ END #############" > $1.new
cat variables.txt > $1.new
echo " " >> functions_dep.txt
echo "############ END #############" >> functions_dep.txt
cat functions.txt >> $1.new
cat functions_dep.txt >> $1.new
erasestring $1 '\#!\/bin\/bash' >> $1.new
messagebox "$1.new saved"
else
	line_break
	colecho "LAZASS was clearly not used in this script" $WARN
fi
rm -f variables.txt
rm -f functions.txt
rm -f functions_dep.txt
thank