#!/bin/bash
#DESCRIPTION_LAZASS: Raspberry Pi Configuration
if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

# MAIN PROGRAM
clear
verify_root
description "Launching Raspberry Pi Configuration"
raspi-config
thank