#!/bin/bash
#DESCRIPTION_LAZASS: Read access log
if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

# MAIN PROGRAM
clear
verify_root
description "READ ACCESS LOG"
console
tail -f /var/log/lighttpd/access.log
console
thank