#!/bin/bash
#DESCRIPTION_LAZASS: Hide PHP Errors
if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

# MAIN PROGRAM
clear
verify_root
description "LIGHTTPD DISPLAY ERROR OFF"
jumpline
colecho "This script will modify PHP.ini to hide error" $INFO
backup_prompt /etc/php5/cgi/php.ini

messagebox "Modifying php.ini"
cat /etc/php5/cgi/php.ini |sed 's/display_errors = On/display_errors = Off/g' > /tmp/php.ini
cp /tmp/php.ini /etc/php5/cgi/php.ini
nlbecho "Modification Completed" 
ok_minibox
line_break
echo "Extract of /etc/php5/cgi/php.ini"
console
cat /etc/php5/cgi/php.ini |grep "display_errors ="
console
thank