#!/bin/bash
#DESCRIPTION_LAZASS: Deactivate HTTPS
if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

# MAIN PROGRAM
clear
verify_root
description "Activate HTTPS"
messagebox "Disable SSL"
rm -vf /etc/lighttpd/conf-enabled/10-ssl.conf
messagebox "Restart Lighttpd"
service lighttpd restart
