#!/bin/bash
#DESCRIPTION_LAZASS: Test a Radio Receiver
if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

# MAIN PROGRAM
clear
verify_root
description "433/315Mhz Radio Receiver Tester"
display_gpio
read -p "GPIO:" gpio
bin/rftester $gpio
thank

