#!/bin/bash
#DESCRIPTION_LAZASS: Choose a configuration
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
        then
        source lib/lazass
else
        echo "------------------------"
        echo "LAZASS was not founded!"
        echo "Installation aborted!"
        echo "------------------------"
        exit 1
fi

##########################################

# MAIN PROGRAM ############################
clear
verify_root
description "Configuring Samba"
installer samba
piname=$(cat /etc/samba/smb.conf |grep "netbios name" |awk '{print $4}')
confmenu "samba" "/etc/samba/smb.conf"
replaceline /etc/samba/smb.conf "netbios name = pi" "        netbios name = $piname" "\[global\]"
restarter samba
thank
