#!/bin/bash
#DESCRIPTION_LAZASS: Delete User
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
        then
        source lib/lazass
else
        echo "------------------------"
        echo "LAZASS was not founded!"
        echo "Installation aborted!"
        echo "------------------------"
        exit 1
fi
##########################################
description "Delete Samba Users"
messagebox "User List"
pdbedit -L|cut -d: -f1
line_break
ask_user "Name of user to delete"
#https://bugzilla.samba.org/show_bug.cgi?id=9981
pdbedit -x $answer
if [ $answer != "pi" ] && [ $answer != "root" ]
	then
	messagebox "System user list"
	list_users
	line_break
	colecho "Would you like to erase $answer from system too ?" $ERR
	continue_prompt
	userdel $answer
fi
restarter samba
thank


