#!/bin/bash
#DESCRIPTION_LAZASS: Uninstall samba
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
        then
        source lib/lazass
else
        echo "------------------------"
        echo "LAZASS was not founded!"
        echo "Installation aborted!"
        echo "------------------------"
        exit 1
fi

##########################################

# MAIN PROGRAM ############################
clear
verify_root
description "Uninstalling Samba"
apt-get remove samba
thank