#!/bin/bash
#DESCRIPTION_LAZASS: Setup Username and Email for Git

if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

# MAIN PROGRAM
clear
verify_root
description "GIT CLIENT CONFIGURATION"

#INSTALL
installer git-core

#NAME ASK
messagebox "GIT CONFIGURATION"
echo "What is your nickname?"
read name
echo ""
echo "What is your github email?"
read email
git config --global user.name "$name"
git config --global user.email "$email"
messagebox "This is your git configuration"
console
git config -l
console
thank