#!/bin/bash
#DESCRIPTION_LAZASS: LIRC Install
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

##########################################

# MAIN PROGRAM ############################
clear
#Verify if you are root
verify_root
description "IR Receiver/Sender Installer"
messagebox "Modify modules"
colecho "We will activate LIRC in the /etc/modules file" $ERR
backup_prompt /etc/modules
cat /etc/modules |sed s'/lirc_dev//'|sed s'/lirc_rpi gpio_in_pin=23 gpio_out_pin=22//' >/tmp/modules
cp -f /tmp/modules /etc/modules
echo "lirc_dev" >> /etc/modules
echo "lirc_rpi gpio_in_pin=23 gpio_out_pin=22" >> /etc/modules
console
cat /etc/modules
console
read
installer lirc
messagebox "Hardware LIRC settings"
backup_prompt /etc/lirc/hardware.conf
cat <<EOF > /etc/lirc/hardware.conf
########################################################
# /etc/lirc/hardware.conf
#
# Arguments which will be used when launching lircd
LIRCD_ARGS="--uinput"

# Don't start lircmd even if there seems to be a good config file
# START_LIRCMD=false

# Don't start irexec, even if a good config file seems to exist.
# START_IREXEC=false

# Try to load appropriate kernel modules
LOAD_MODULES=true

# Run "lircd --driver=help" for a list of supported drivers.
DRIVER="default"
# usually /dev/lirc0 is the correct setting for systems using udev
DEVICE="/dev/lirc0"
MODULES="lirc_rpi"

# Default configuration files for your hardware if any
LIRCD_CONF=""
LIRCMD_CONF=""
########################################################
EOF
console
cat /etc/lirc/hardware.conf
console
read
messagebox "Wiring"
display_gpio
colecho "IR Receiver : GPIO 4" $WARN
colecho "IR LED : GPIO 3" $WARN
colecho "We will stop the Raspberry Pi now, so you can plug the cable" $ERR
colecho "You can modify gpio inside /etc/modules" $INFO
colecho "Even if you have already wired everything, you still have to reboot" $INFO
continue_prompt
halt
thank

