#!/bin/bash
#DESCRIPTION_LAZASS: Change password
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
        then
        source lib/lazass
else
        echo "------------------------"
        echo "LAZASS was not founded!"
        echo "Installation aborted!"
        echo "------------------------"
        exit 1
fi
##########################################
description "Add User"
messagebox "System User List"
list_users
line_break
ask_user "User's name:"
console
passwd $answer
console
thank
