#!/bin/bash
#DESCRIPTION_LAZASS: Delete User
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi
##########################################
description "Delete User"
messagebox "System user list"
list_users
line_break
ask_user "User to delete"
if [ $answer != "pi" ] && [ $answer != "root" ]
	then
	continue_prompt
	userdel $answer
else
	jumpline
	colecho "I can't erase this user" $ERR
	colecho "If you know what you are doing type:" $WARN
	console
	colecho "userdel $answer" $PICOLOR
	console
fi
thank


