#!/bin/bash
#DESCRIPTION_LAZASS: Create a static IP conf from a DHCP conf
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

##########################################

# MAIN PROGRAM ############################
clear
interfaces=$(ifconfig |grep "Link"|awk '{print $1}')
interface=$(whiptail --inputbox "Network card\n-----------\n$interfaces" 0 0 "eth0" 3>&1 1>&2 2>&3)

ipaddress=$(hostname -I |awk {'print $1'});
netmask=$(ifconfig $interface |head -n2|tail -n1|awk '{print $4}'|sed -e 's/'Mask:'//'|sed -e 's/'Masque:'//')
broadcast=$(ifconfig $interface |head -n2|tail -n1|awk '{print $3}'|sed -e 's/'Bcast:'//')
gateway=$(route -n |grep "0.0.0.0" |awk '{ print $2}'|head -n1)

ip_choice=$(whiptail --inputbox "IP Address - "$ipaddress 0 0 $ipaddress 3>&1 1>&2 2>&3)

clear
echo -e "Copy this in /etc/network/interfaces\n\niface $interface inet static\n address $ip_choice\n netmask $netmask\n broadcast $broadcast\n gateway $gateway"
