#!/bin/bash
#DESCRIPTION_LAZASS: Serial USB Tester
########## LAZASS LIBRARY ###################

if [ -f lib/lazass ]
	then
	source lib/lazass
else
	echo "------------------------"
	echo "LAZASS was not founded!"
	echo "Installation aborted!"
	echo "------------------------"
	exit 1
fi

##########################################

# MAIN PROGRAM ############################
clear
#Verify if you are root
verify_root
description "Serial Test"
messagebox "Launching Minicom"
colecho "We are going to launch minicom to verify if the transmission are correct" $INFO
colecho "To exit minicom press CTRL-A x" $ERR
installer minicom
messagebox "List of Serial Port"
console
ls /dev/ttyAMA* /dev/ttyUSB* /dev/ttyACM* /dev/ttyS* 2>/dev/null
console
echo "Serial Port:"
read port
minicom -b 9600 -o -D $port
thank
